### ISSUE TITLE
Where should I upload my sequence data?

### ISSUE THREAD

**Issue by CoronelVargasG** [egochao/DeePromoter#1]
Dear egochao,
I belived that the command python3 test.py -d data/human/nonTATA/hs_pos_nonTATA.txt -w data/myDNAsequence.txt was enought to  load my sequence. But I got an error. Would you be more specific where should I upload my sequece data? 
I'm a beginner with pytorch so the script is not clear to me.

Thanks!

**Comment by egochao** [comment]
Hi @CoronelVargasG the command is correct. Can you provide more detail about your error. And please check the data format, make sure it follow the test data format.
